// Code generated by protoc-gen-go.
// source: Handshake.proto
// DO NOT EDIT!

/*
Package message is a generated protocol buffer package.

It is generated from these files:
	Handshake.proto

It has these top-level messages:
	Handshake
*/
package message

import proto "code.google.com/p/goprotobuf/proto"
import json "encoding/json"
import math "math"

// Reference proto, json, and math imports to suppress error if they are not otherwise used.
var _ = proto.Marshal
var _ = &json.SyntaxError{}
var _ = math.Inf

type Handshake struct {
	RequestTime      *string `protobuf:"bytes,2,opt,name=request_time" json:"request_time,omitempty"`
	ResponseTime     *string `protobuf:"bytes,3,opt,name=response_time" json:"response_time,omitempty"`
	ServerStatu      *uint32 `protobuf:"varint,4,opt,name=server_statu" json:"server_statu,omitempty"`
	Desction         *string `protobuf:"bytes,5,opt,name=desction" json:"desction,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Handshake) Reset()         { *m = Handshake{} }
func (m *Handshake) String() string { return proto.CompactTextString(m) }
func (*Handshake) ProtoMessage()    {}

func (m *Handshake) GetRequestTime() string {
	if m != nil && m.RequestTime != nil {
		return *m.RequestTime
	}
	return ""
}

func (m *Handshake) GetResponseTime() string {
	if m != nil && m.ResponseTime != nil {
		return *m.ResponseTime
	}
	return ""
}

func (m *Handshake) GetServerStatu() uint32 {
	if m != nil && m.ServerStatu != nil {
		return *m.ServerStatu
	}
	return 0
}

func (m *Handshake) GetDesction() string {
	if m != nil && m.Desction != nil {
		return *m.Desction
	}
	return ""
}

func init() {
}
